name: Release

on:
  release:
    types: [published]

permissions:
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            TRACER_VERSION=${{ github.ref_name }}
            TRACER_COMMIT=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64,linux/amd64
          provenance: false
          tags: |
            ghcr.io/ivov/n8n-tracer:latest
            ghcr.io/ivov/n8n-tracer:${{ github.ref_name }}
